---
title: "Action Asymmetry Experiment (n = 1008): Demographics analyses"
pagetitle: "aah | exp | analysis (demographics)"
author: "Owen Morgan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

<style type="text/css">
  body{
  font-family: Avenir;
  font-size: 12pt;
}
</style>

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", fig.width = 9,
                      fig.height = 6, results = "asis")
options(knitr.kable.NA = "")

cli.progress_show_after <- 0

## Do not use scientific notation until 9 decimal places.
options(scipen = 9, digits = 9)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

```{r lib}
library(here)
library(tidyverse)
library(cli) # For printing error messages

library(lme4)
library(emmeans)
library(broom)
library(gt)

# library(ggpubr) ## functions for plotting SD, SEM, CI.
# library(ggbeeswarm)
# library(patchwork)
# library(ggh4x) ## for nested facets

library(knitr) # For include_graphics

source(here::here("lib", "load_process", "load_process.R"))
source(here::here("lib", "util.R"))
source(here::here("lib", "demographics.R"))
source(here::here("lib", "plots.R"))

## Colors for plots
plot_blue <- c("#337aB7")
plot_colors <- c("#4477AA",
                 "#EE6677",
                 "#CCBB44",
                 "#66CCEE",
                 "#AA3377",
                 "#228833",
                 "#BBBBBB")
```

```{r config}
proc_dir <- here::here("data", "proc_exp_n1008")
```

```{r load_data}
## Load "the data" with all subjects & trials
aah_long <- load_aah_long(proc_dir)

## Load summary data table (for quick demographic analyses)
## with all subjects.
aah_summary_all <- load_aah_summary(proc_dir)
```

```{r prepare_data}
#### PREPARE SUMMARY DATA FOR DEMOGRAPHICS ANALYSES
aah_summary <- filter_aah_summary_for_analysis(aah_summary_all)
```


Demographics for included participants, by handedness group (EHI bins). 
```{r}
hand_demo_summary_table(aah_summary) |> pretty_table() |>
  tab_footnote("Left: (EHI <= -40)  |  Mixed: (-40 < EHI < 40)  |  Right: (EHI >= 40)")

## Save as latex object
# out_table <- hand_demo_summary_table(aah_summary) |> pretty_table() |>
#   tab_footnote("Left: (EHI <= -40)  |  Mixed: (-40 < EHI < 40)  |  Right: (EHI >= 40)")
# here("tables")
# gt::gtsave(out_table, filename = "table1.tex", path = here("tables"))
```
<br>
Any group differences?
<br>
```{r}
lm(data = aah_summary, formula = age ~ handedness) |> 
  emmeans(~ handedness) |> 
  contrast("pairwise") |> 
  summary(infer = T, adj = "none") |>
  as_tibble() |> 
  pretty_table("Age (years)")
```
<br>
```{r}
lm(data = aah_summary, formula = education ~ handedness) |> 
  emmeans(~ handedness) |> 
  contrast("pairwise") |> 
  summary(infer = T, adj = "none") |>
  as_tibble() |> 
  pretty_table("Education (years)")
```
<br>
```{r}
sex_data <- aah_summary |> filter(sex %in% c("Male", "Female")) |> 
  mutate(sex = as.factor(sex))

glm(data = sex_data,
    formula = sex ~ handedness,
    family = "binomial") |> 
  emmeans(~ handedness) |>
  contrast("pairwise") |>
  summary(infer = T, adj = "none", type = "response") |>
  as_tibble() |>
  pretty_table("Sex") |> 
  tab_footnote(footnote = "Odds (female / male)",
               locations = cells_column_labels(columns = "odds.ratio"))
```





